
package stubs.validatepass;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ValidatePassWebServiceImplService", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/aa", wsdlLocation = "file:///home/lucas/Isola3000/aa/client/src/main/resources/ValidatePassWS.wsdl")
public class ValidatePassWebServiceImplService
    extends Service
{

    private final static URL VALIDATEPASSWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException VALIDATEPASSWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName VALIDATEPASSWEBSERVICEIMPLSERVICE_QNAME = new QName("http://www.polytech.unice.fr/si/4a/isa/aa", "ValidatePassWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:///home/lucas/Isola3000/aa/client/src/main/resources/ValidatePassWS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALIDATEPASSWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        VALIDATEPASSWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ValidatePassWebServiceImplService() {
        super(__getWsdlLocation(), VALIDATEPASSWEBSERVICEIMPLSERVICE_QNAME);
    }

    public ValidatePassWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDATEPASSWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public ValidatePassWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, VALIDATEPASSWEBSERVICEIMPLSERVICE_QNAME);
    }

    public ValidatePassWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDATEPASSWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public ValidatePassWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidatePassWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ValidatePassWebService
     */
    @WebEndpoint(name = "ValidatePassWebServiceImplPort")
    public ValidatePassWebService getValidatePassWebServiceImplPort() {
        return super.getPort(new QName("http://www.polytech.unice.fr/si/4a/isa/aa", "ValidatePassWebServiceImplPort"), ValidatePassWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidatePassWebService
     */
    @WebEndpoint(name = "ValidatePassWebServiceImplPort")
    public ValidatePassWebService getValidatePassWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytech.unice.fr/si/4a/isa/aa", "ValidatePassWebServiceImplPort"), ValidatePassWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDATEPASSWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw VALIDATEPASSWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return VALIDATEPASSWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
