
package stubs.purchaseobjects;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AlreadyExistingCard", targetNamespace = "http://webservice.aa.isa.fr.unice.polytech/")
public class AlreadyExistingCard_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AlreadyExistingCard faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AlreadyExistingCard_Exception(String message, AlreadyExistingCard faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AlreadyExistingCard_Exception(String message, AlreadyExistingCard faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: stubs.purchaseobjects.AlreadyExistingCard
     */
    public AlreadyExistingCard getFaultInfo() {
        return faultInfo;
    }

}
