
package stubs.purchaseobjects;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PurchaseWebService", targetNamespace = "http://webservice.aa.isa.fr.unice.polytech/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PurchaseWebService {


    /**
     * 
     * @param numCreditcard
     * @return
     *     returns java.lang.String
     * @throws UnknownUserException_Exception
     * @throws PaymentException_Exception
     * @throws AlreadyExistingCard_Exception
     */
    @WebMethod
    @WebResult(name = "id_card", targetNamespace = "")
    @RequestWrapper(localName = "getCard", targetNamespace = "http://webservice.aa.isa.fr.unice.polytech/", className = "stubs.purchaseobjects.GetCard")
    @ResponseWrapper(localName = "getCardResponse", targetNamespace = "http://webservice.aa.isa.fr.unice.polytech/", className = "stubs.purchaseobjects.GetCardResponse")
    public String getCard(
        @WebParam(name = "num_creditcard", targetNamespace = "")
        String numCreditcard)
        throws AlreadyExistingCard_Exception, PaymentException_Exception, UnknownUserException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<stubs.purchaseobjects.AbstractPass>
     */
    @WebMethod
    @WebResult(name = "pass", targetNamespace = "")
    @RequestWrapper(localName = "listAllPass", targetNamespace = "http://webservice.aa.isa.fr.unice.polytech/", className = "stubs.purchaseobjects.ListAllPass")
    @ResponseWrapper(localName = "listAllPassResponse", targetNamespace = "http://webservice.aa.isa.fr.unice.polytech/", className = "stubs.purchaseobjects.ListAllPassResponse")
    public List<AbstractPass> listAllPass();

    /**
     * 
     * @param zone
     * @param idCard
     * @param type
     * @param numCreditcard
     * @param age
     * @throws PaymentException_Exception
     * @throws UnknownCardException_Exception
     * @throws UnknownPass_Exception
     * @throws PriceNotFoundException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addPassForCardWithCredential", targetNamespace = "http://webservice.aa.isa.fr.unice.polytech/", className = "stubs.purchaseobjects.AddPassForCardWithCredential")
    @ResponseWrapper(localName = "addPassForCardWithCredentialResponse", targetNamespace = "http://webservice.aa.isa.fr.unice.polytech/", className = "stubs.purchaseobjects.AddPassForCardWithCredentialResponse")
    public void addPassForCardWithCredential(
        @WebParam(name = "id_card", targetNamespace = "")
        String idCard,
        @WebParam(name = "age", targetNamespace = "")
        String age,
        @WebParam(name = "type", targetNamespace = "")
        String type,
        @WebParam(name = "zone", targetNamespace = "")
        String zone,
        @WebParam(name = "num_creditcard", targetNamespace = "")
        String numCreditcard)
        throws PaymentException_Exception, PriceNotFoundException_Exception, UnknownCardException_Exception, UnknownPass_Exception
    ;

    /**
     * 
     * @param userFirstname
     * @param userName
     * @return
     *     returns java.lang.String
     * @throws PaymentException_Exception
     * @throws UnknownUserException_Exception
     * @throws AlreadyExistingCard_Exception
     */
    @WebMethod
    @WebResult(name = "id_card", targetNamespace = "")
    @RequestWrapper(localName = "addCardForUser", targetNamespace = "http://webservice.aa.isa.fr.unice.polytech/", className = "stubs.purchaseobjects.AddCardForUser")
    @ResponseWrapper(localName = "addCardForUserResponse", targetNamespace = "http://webservice.aa.isa.fr.unice.polytech/", className = "stubs.purchaseobjects.AddCardForUserResponse")
    public String addCardForUser(
        @WebParam(name = "user_name", targetNamespace = "")
        String userName,
        @WebParam(name = "user_firstname", targetNamespace = "")
        String userFirstname)
        throws AlreadyExistingCard_Exception, PaymentException_Exception, UnknownUserException_Exception
    ;

    /**
     * 
     * @param idCard
     * @throws PaymentException_Exception
     * @throws UnknownCardException_Exception
     * @throws UnknownPass_Exception
     * @throws PriceNotFoundException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "subscribeFidelicime", targetNamespace = "http://webservice.aa.isa.fr.unice.polytech/", className = "stubs.purchaseobjects.SubscribeFidelicime")
    @ResponseWrapper(localName = "subscribeFidelicimeResponse", targetNamespace = "http://webservice.aa.isa.fr.unice.polytech/", className = "stubs.purchaseobjects.SubscribeFidelicimeResponse")
    public void subscribeFidelicime(
        @WebParam(name = "id_card", targetNamespace = "")
        String idCard)
        throws PaymentException_Exception, PriceNotFoundException_Exception, UnknownCardException_Exception, UnknownPass_Exception
    ;

    /**
     * 
     * @param zone
     * @param idCard
     * @param type
     * @param age
     * @throws PaymentException_Exception
     * @throws UnknownCardException_Exception
     * @throws UnknownPass_Exception
     * @throws PriceNotFoundException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addPassForCard", targetNamespace = "http://webservice.aa.isa.fr.unice.polytech/", className = "stubs.purchaseobjects.AddPassForCard")
    @ResponseWrapper(localName = "addPassForCardResponse", targetNamespace = "http://webservice.aa.isa.fr.unice.polytech/", className = "stubs.purchaseobjects.AddPassForCardResponse")
    public void addPassForCard(
        @WebParam(name = "id_card", targetNamespace = "")
        String idCard,
        @WebParam(name = "age", targetNamespace = "")
        String age,
        @WebParam(name = "type", targetNamespace = "")
        String type,
        @WebParam(name = "zone", targetNamespace = "")
        String zone)
        throws PaymentException_Exception, PriceNotFoundException_Exception, UnknownCardException_Exception, UnknownPass_Exception
    ;

}
