
package stubs.purchaseobjects;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UnknownCardException", targetNamespace = "http://webservice.aa.isa.fr.unice.polytech/")
public class UnknownCardException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnknownCardException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UnknownCardException_Exception(String message, UnknownCardException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public UnknownCardException_Exception(String message, UnknownCardException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: stubs.purchaseobjects.UnknownCardException
     */
    public UnknownCardException getFaultInfo() {
        return faultInfo;
    }

}
