
package stubs.usermodifier;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AlreadyExistingUserException", targetNamespace = "http://webservice.aa.isa.fr.unice.polytech/")
public class AlreadyExistingUserException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AlreadyExistingUserException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AlreadyExistingUserException_Exception(String message, AlreadyExistingUserException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AlreadyExistingUserException_Exception(String message, AlreadyExistingUserException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: stubs.usermodifier.AlreadyExistingUserException
     */
    public AlreadyExistingUserException getFaultInfo() {
        return faultInfo;
    }

}
