
package stubs.usermodifier;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserModifierWebServiceImplService", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/aa", wsdlLocation = "file:///home/lucas/Isola3000/aa/client/src/main/resources/UserModifierWS.wsdl")
public class UserModifierWebServiceImplService
    extends Service
{

    private final static URL USERMODIFIERWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERMODIFIERWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName USERMODIFIERWEBSERVICEIMPLSERVICE_QNAME = new QName("http://www.polytech.unice.fr/si/4a/isa/aa", "UserModifierWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:///home/lucas/Isola3000/aa/client/src/main/resources/UserModifierWS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERMODIFIERWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        USERMODIFIERWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public UserModifierWebServiceImplService() {
        super(__getWsdlLocation(), USERMODIFIERWEBSERVICEIMPLSERVICE_QNAME);
    }

    public UserModifierWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERMODIFIERWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public UserModifierWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, USERMODIFIERWEBSERVICEIMPLSERVICE_QNAME);
    }

    public UserModifierWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERMODIFIERWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public UserModifierWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserModifierWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserModifierWebService
     */
    @WebEndpoint(name = "UserModifierWebServiceImplPort")
    public UserModifierWebService getUserModifierWebServiceImplPort() {
        return super.getPort(new QName("http://www.polytech.unice.fr/si/4a/isa/aa", "UserModifierWebServiceImplPort"), UserModifierWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserModifierWebService
     */
    @WebEndpoint(name = "UserModifierWebServiceImplPort")
    public UserModifierWebService getUserModifierWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytech.unice.fr/si/4a/isa/aa", "UserModifierWebServiceImplPort"), UserModifierWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERMODIFIERWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw USERMODIFIERWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return USERMODIFIERWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
