
package stubs.usermodifier;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserModifierWebService", targetNamespace = "http://webservice.aa.isa.fr.unice.polytech/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserModifierWebService {


    /**
     * 
     * @param userFirstname
     * @param userName
     * @return
     *     returns java.util.List<stubs.usermodifier.Transaction>
     */
    @WebMethod
    @WebResult(name = "alltransactions", targetNamespace = "")
    @RequestWrapper(localName = "getHistory", targetNamespace = "http://webservice.aa.isa.fr.unice.polytech/", className = "stubs.usermodifier.GetHistory")
    @ResponseWrapper(localName = "getHistoryResponse", targetNamespace = "http://webservice.aa.isa.fr.unice.polytech/", className = "stubs.usermodifier.GetHistoryResponse")
    public List<Transaction> getHistory(
        @WebParam(name = "user_name", targetNamespace = "")
        String userName,
        @WebParam(name = "user_firstname", targetNamespace = "")
        String userFirstname);

    /**
     * 
     * @param mail
     * @param creditCardNumber
     * @param userFirstname
     * @param userName
     * @param age
     * @throws AlreadyExistingUserException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "register", targetNamespace = "http://webservice.aa.isa.fr.unice.polytech/", className = "stubs.usermodifier.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://webservice.aa.isa.fr.unice.polytech/", className = "stubs.usermodifier.RegisterResponse")
    public void register(
        @WebParam(name = "user_name", targetNamespace = "")
        String userName,
        @WebParam(name = "user_firstname", targetNamespace = "")
        String userFirstname,
        @WebParam(name = "age", targetNamespace = "")
        int age,
        @WebParam(name = "credit_card_number", targetNamespace = "")
        String creditCardNumber,
        @WebParam(name = "mail", targetNamespace = "")
        String mail)
        throws AlreadyExistingUserException_Exception
    ;

}
